deprecated: true
description: 'GitLab. Collaboration and source control management: code, test, and
  deploy together!'
home: https://about.gitlab.com
icon: https://gitlab.com/uploads/group/avatar/6543/gitlab-logo-square.png
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
- name: DJ Mountney
name: gitlab
sources:
- https://hub.docker.com/r/gitlab/gitlab-ce/
- https://hub.docker.com/r/gitlab/gitlab-ee/
- https://docs.gitlab.com/omnibus/
version: 0.1.10
